#!/usr/bin/env bash
# detect-stack.sh [project-dir]
# Fast, read-only inventory of a project's technologies. Prints Markdown.
# It is a starting point for reconnaissance, not the final truth: verify
# anything that matters by reading the files it points to.
# Never prints secret values: env files are read for variable NAMES only,
# and real .env files are only reported as present.

set -uo pipefail
ROOT="${1:-.}"
cd "$ROOT" || { echo "cannot cd to $ROOT" >&2; exit 1; }

PRUNE=( -name node_modules -o -name .git -o -name .next -o -name .nuxt -o -name dist -o -name build
        -o -name out -o -name .venv -o -name venv -o -name env -o -name __pycache__ -o -name Pods
        -o -name .expo -o -name .turbo -o -name coverage -o -name .devrun -o -name vendor
        -o -name target -o -name .gradle -o -name .dart_tool -o -name .svelte-kit -o -name .cache
        -o -name DerivedData -o -name .output -o -name .vercel )

ff() { # ff <maxdepth> <find name expr...> : list matching files, pruned
  local depth="$1"; shift
  find . -maxdepth "$depth" \( "${PRUNE[@]}" \) -prune -o -type f \( "$@" \) -print 2>/dev/null \
    | sed 's|^\./||' | sort
}
fd() { # fd <maxdepth> <name>: list matching dirs, pruned
  find . -maxdepth "$1" \( "${PRUNE[@]}" \) -prune -o -type d -name "$2" -print 2>/dev/null | sed 's|^\./||' | sort
}
has() { command -v "$1" >/dev/null 2>&1; }
section() { printf '\n## %s\n' "$1"; }
bullet() { printf -- '- %s\n' "$1"; }

echo "# Stack detection: $(basename "$(pwd)")"
echo "_Generated by detect-stack.sh on $(date -u +%Y-%m-%dT%H:%MZ). Verify before relying on it._"

# ---------------------------------------------------------------- manifests
section "Manifests"
mapfile -t PKGS < <(ff 4 -name package.json | head -25)
mapfile -t PYREQ < <(ff 4 -name 'requirements*.txt' -o -name pyproject.toml -o -name Pipfile -o -name setup.py | head -15)
mapfile -t OTHER < <(ff 4 -name pubspec.yaml -o -name go.mod -o -name Cargo.toml -o -name composer.json \
  -o -name Gemfile -o -name pom.xml -o -name 'build.gradle' -o -name 'build.gradle.kts' -o -name Podfile \
  -o -name Package.swift -o -name '*.csproj' -o -name deno.json -o -name bun.lockb | head -20)
for f in "${PKGS[@]}" "${PYREQ[@]}" "${OTHER[@]}"; do [ -n "$f" ] && bullet "$f"; done
[ ${#PKGS[@]} -eq 0 ] && [ ${#PYREQ[@]} -eq 0 ] && [ ${#OTHER[@]} -eq 0 ] && bullet "none found (depth 4)"

section "Package managers / lockfiles"
for lf in package-lock.json pnpm-lock.yaml yarn.lock bun.lockb bun.lock poetry.lock uv.lock Pipfile.lock pdm.lock \
          pubspec.lock Podfile.lock go.sum Cargo.lock composer.lock Gemfile.lock; do
  found=$(ff 3 -name "$lf" | head -3 | tr '\n' ' ')
  [ -n "$found" ] && bullet "$lf: $found"
done

section "Monorepo"
mono=""
for m in pnpm-workspace.yaml turbo.json nx.json lerna.json rush.json; do [ -f "$m" ] && mono+="$m "; done
[ -f package.json ] && grep -q '"workspaces"' package.json 2>/dev/null && mono+="package.json#workspaces "
[ -n "$mono" ] && bullet "yes: $mono" || bullet "no markers at root"

# ------------------------------------------------------------ JS / TS deps
JS_DEPS=(
  # frameworks & routing
  next react react-dom vue nuxt svelte @sveltejs/kit @angular/core solid-js astro @remix-run/react
  react-router-dom react-router @tanstack/react-router @tanstack/react-query swr zustand @reduxjs/toolkit jotai
  # ui & styling
  tailwindcss @tailwindcss/postcss @mui/material @chakra-ui/react styled-components @radix-ui/react-slot
  framer-motion motion gsap three @react-three/fiber i18next react-i18next next-intl
  # backend
  express @nestjs/core fastify hono koa @trpc/server graphql @apollo/server socket.io ws bullmq ioredis redis
  # data
  prisma @prisma/client mongoose mongodb drizzle-orm typeorm sequelize pg mysql2 better-sqlite3
  @supabase/supabase-js firebase firebase-admin
  # auth & payments & comms
  next-auth @auth/core @clerk/nextjs better-auth passport jsonwebtoken stripe @stripe/stripe-js resend nodemailer
  # AI / LLM
  openai @anthropic-ai/sdk @google/genai @google/generative-ai ai @ai-sdk/openai @ai-sdk/anthropic @ai-sdk/google
  langchain @langchain/core @langchain/langgraph llamaindex @pinecone-database/pinecone @qdrant/js-client-rest
  chromadb @modelcontextprotocol/sdk replicate @fal-ai/client @fal-ai/serverless-client @huggingface/inference
  # mobile / desktop
  react-native expo expo-router @react-navigation/native @shopify/flash-list electron @capacitor/core
  # build, quality, tests
  typescript vite webpack turbo eslint prettier @biomejs/biome zod jest vitest @playwright/test playwright
  cypress detox @testing-library/react @testing-library/react-native supertest msw
)
if [ ${#PKGS[@]} -gt 0 ]; then
  section "JS/TS dependencies of interest"
  for pj in "${PKGS[@]}"; do
    hits=""
    for dep in "${JS_DEPS[@]}"; do
      esc=$(printf '%s' "$dep" | sed 's/[.[\*^$/]/\\&/g')
      v=$(grep -Eo "\"$esc\"[[:space:]]*:[[:space:]]*\"[^\"]+\"" "$pj" 2>/dev/null | head -1 \
          | sed -E 's/.*:[[:space:]]*"([^"]+)"/\1/')
      [ -n "$v" ] && hits+="$dep@$v, "
    done
    [ -n "$hits" ] && printf -- '- **%s**: %s\n' "$pj" "${hits%, }"
  done

  section "Scripts (package.json)"
  for pj in "${PKGS[@]:0:10}"; do
    if has node; then
      s=$(node -e 'try{const s=require(require("path").resolve(process.argv[1])).scripts||{};
        console.log(Object.entries(s).map(([k,v])=>`${k}: ${v}`).join("\n"))}catch(e){}' "$pj" 2>/dev/null)
    elif has python3; then
      s=$(python3 -c 'import json,sys
try:
  s=json.load(open(sys.argv[1])).get("scripts",{})
  print("\n".join(f"{k}: {v}" for k,v in s.items()))
except Exception: pass' "$pj" 2>/dev/null)
    else s=""; fi
    if [ -n "$s" ]; then
      printf -- '- **%s**\n' "$pj"
      printf '%s\n' "$s" | head -25 | sed 's/^/  - `/; s/$/`/'
    fi
  done
fi

# ------------------------------------------------------------- Python deps
PY_DEPS=( fastapi django djangorestframework flask starlette uvicorn gunicorn sqlalchemy sqlmodel alembic
  pydantic pydantic-settings celery rq dramatiq redis psycopg psycopg2 psycopg2-binary asyncpg motor pymongo beanie
  openai anthropic google-genai google-generativeai langchain langchain-core langgraph llama-index
  transformers torch sentence-transformers pinecone pinecone-client qdrant-client chromadb pgvector
  fal-client replicate pytest pytest-asyncio httpx requests boto3 stripe )
if [ ${#PYREQ[@]} -gt 0 ]; then
  section "Python dependencies of interest"
  for rf in "${PYREQ[@]}"; do
    hits=""
    for dep in "${PY_DEPS[@]}"; do
      # quoted anywhere on a line (pyproject arrays, incl. single-line) ...
      line=$(grep -Eio "\"$dep(\[[^]]*\])?([[:space:]]*[<>=~!^]=?[^\"]*)?\"" "$rf" 2>/dev/null | head -1 | tr -d ' "')
      # ... or unquoted at line start (requirements.txt)
      [ -z "$line" ] && line=$(grep -Eio "^[[:space:]]*$dep(\[[^]]*\])?([[:space:]]*[<>=~!^]=?[^,;#[:space:]]*)?[[:space:]]*(,|;|#|\$)" "$rf" 2>/dev/null | head -1 \
             | tr -d ' ",;#' )
      [ -z "$line" ] && line=$(grep -Eio "^$dep[[:space:]]*=[[:space:]]*[\"{][^\"}]*" "$rf" 2>/dev/null | head -1 | tr -d ' "{')
      [ -n "$line" ] && hits+="$line, "
    done
    [ -n "$hits" ] && printf -- '- **%s**: %s\n' "$rf" "${hits%, }"
  done
fi

# --------------------------------------------------------- other ecosystems
if [ ${#OTHER[@]} -gt 0 ]; then
  section "Other ecosystems"
  for f in "${OTHER[@]}"; do
    case "$f" in
      *pubspec.yaml)
        sdk=$(grep -E '^[[:space:]]+(sdk|flutter):' "$f" | head -2 | tr -s ' ' | tr '\n' ' ')
        deps=$(grep -Eo '^[[:space:]]{2}(flutter_riverpod|riverpod|flutter_bloc|provider|get|go_router|dio|http|firebase_core|supabase_flutter|google_generative_ai|flutter_localizations)[[:space:]]*:' "$f" | tr -d ' :' | tr '\n' ' ')
        bullet "Flutter/Dart ($f): ${sdk}${deps:+deps: $deps}" ;;
      *go.mod) bullet "Go ($f): $(head -1 "$f"); $(grep -E '^go ' "$f")" ;;
      *) bullet "$f" ;;
    esac
  done
fi

# ------------------------------------------------------------ project shape
section "Project shape & framework configs"
mapfile -t FWCFG < <(ff 4 -name 'next.config.*' -o -name 'vite.config.*' -o -name 'nuxt.config.*' -o -name 'svelte.config.*' \
  -o -name 'astro.config.*' -o -name angular.json -o -name 'tailwind.config.*' -o -name 'postcss.config.*' \
  -o -name 'metro.config.*' -o -name 'app.config.js' -o -name 'app.config.ts' -o -name eas.json -o -name nest-cli.json \
  -o -name manage.py -o -name alembic.ini -o -name 'schema.prisma' -o -name 'drizzle.config.*' | head -25)
for f in "${FWCFG[@]}"; do [ -n "$f" ] && bullet "$f"; done
# Expo app.json files (only those that mention expo)
while IFS= read -r f; do [ -n "$f" ] && grep -q '"expo"' "$f" 2>/dev/null && bullet "$f (Expo app config)"; done < <(ff 4 -name app.json)
# Routing style next to each Next.js config
for cfg in "${FWCFG[@]}"; do
  case "$cfg" in *next.config.*)
    base=$(dirname "$cfg")
    { [ -d "$base/app" ] || [ -d "$base/src/app" ]; } && bullet "$base: Next.js App Router (app/ dir)"
    { [ -d "$base/pages" ] || [ -d "$base/src/pages" ]; } && bullet "$base: Next.js Pages Router (pages/ dir)" ;;
  esac
done
while IFS= read -r d; do [ -n "$d" ] && bullet "$d/ native project present (bare React Native / prebuilt Expo / Flutter)"; done \
  < <(fd 3 ios; fd 3 android)
mapfile -t APPDIRS < <(for d in apps packages services backend frontend server client web mobile api; do [ -d "$d" ] && echo "$d"; done)
[ ${#APPDIRS[@]} -gt 0 ] && bullet "top-level app dirs: ${APPDIRS[*]}"

section "Infra, deploy & CI"
mapfile -t INFRA < <(ff 3 -name 'Dockerfile*' -o -name 'docker-compose*.yml' -o -name 'docker-compose*.yaml' \
  -o -name 'compose.yml' -o -name 'compose.yaml' -o -name vercel.json -o -name netlify.toml -o -name fly.toml \
  -o -name render.yaml -o -name railway.json -o -name serverless.yml -o -name firebase.json -o -name Procfile \
  -o -name Chart.yaml -o -name '*.tf' -o -name .gitlab-ci.yml -o -name cloudbuild.yaml -o -name app.yaml \
  -o -name nginx.conf -o -name Makefile -o -name Taskfile.yml -o -name justfile | head -25)
mapfile -t CI < <(ff 3 -path './.github/workflows/*' | head -10)
for f in "${INFRA[@]}" "${CI[@]}"; do [ -n "$f" ] && bullet "$f"; done
[ -f Makefile ] && bullet "Makefile targets: $(grep -Eo '^[a-zA-Z0-9_.-]+:' Makefile | tr -d ':' | head -15 | tr '\n' ' ')"
if [ ${#INFRA[@]} -eq 0 ] && [ ${#CI[@]} -eq 0 ]; then bullet "none found"; fi

section "Tests"
mapfile -t TCFG < <(ff 3 -name 'jest.config.*' -o -name 'vitest.config.*' -o -name 'playwright.config.*' \
  -o -name 'cypress.config.*' -o -name pytest.ini -o -name conftest.py -o -name '.detoxrc*' -o -name tox.ini | head -12)
for f in "${TCFG[@]}"; do [ -n "$f" ] && bullet "$f"; done
[ -d .maestro ] && bullet ".maestro/ (Maestro mobile flows)"
ntests=$(ff 6 -name '*.test.*' -o -name '*.spec.*' -o -name 'test_*.py' -o -name '*_test.py' -o -name '*_test.go' -o -name '*_test.dart' | wc -l | tr -d ' ')
bullet "test files found: $ntests"

section "Environment variables (names only)"
mapfile -t ENVEX < <(ff 3 -name '.env.example' -o -name '.env.sample' -o -name '.env.template' -o -name '.env.local.example' -o -name 'example.env' | head -6)
for f in "${ENVEX[@]}"; do
  [ -z "$f" ] && continue
  names=$(grep -Eo '^[[:space:]]*(export[[:space:]]+)?[A-Z][A-Z0-9_]*[[:space:]]*=' "$f" | sed -E 's/^[[:space:]]*(export[[:space:]]+)?//; s/[[:space:]]*=//' | tr '\n' ' ')
  bullet "$f: $names"
done
mapfile -t ENVREAL < <(ff 3 -name '.env' -o -name '.env.local' -o -name '.env.development' -o -name '.env.production' | head -6)
[ ${#ENVREAL[@]} -gt 0 ] && [ -n "${ENVREAL[0]}" ] && bullet "real env files present (not read): ${ENVREAL[*]}"
[ ${#ENVEX[@]} -eq 0 ] && [ ${#ENVREAL[@]} -eq 0 ] && bullet "no env files found"

section "AI / LLM usage in source"
SRC_INC=( --include='*.ts' --include='*.tsx' --include='*.js' --include='*.jsx' --include='*.mjs' --include='*.py'
          --include='*.dart' --include='*.go' --include='*.json' --include='*.yaml' --include='*.yml' --include='*.env.example' )
EXCL=( --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=.next --exclude-dir=dist --exclude-dir=build
       --exclude-dir=.venv --exclude-dir=venv --exclude-dir=.devrun --exclude-dir=coverage --exclude-dir=Pods
       --exclude=package-lock.json --exclude=pnpm-lock.yaml --exclude=yarn.lock )
models=$(grep -rEoh "${SRC_INC[@]}" "${EXCL[@]}" \
  '\b(fal-ai/[a-z0-9./-]+|gpt-[0-9][a-z0-9.-]*|o[1-9](-[a-z]+)?|claude-[a-z0-9.-]+|gemini-[0-9][a-z0-9.-]*|llama-?[0-9][a-z0-9.-]*|mistral-[a-z0-9.-]+|deepseek-[a-z0-9.-]+|grok-[0-9a-z.-]+|qwen[0-9a-z.-]*|text-embedding-[a-z0-9-]+|dall-e-[0-9]|flux[-/][a-z0-9./-]+|imagen-[0-9a-z.-]+|veo-[0-9a-z.-]+|kling[a-z0-9./-]*|seedance[a-z0-9./-]*)\b' . 2>/dev/null \
  | sort | uniq -c | sort -rn | head -15 | awk '{printf "%s (x%s), ", $2, $1}')
[ -n "$models" ] && bullet "model IDs referenced: ${models%, }" || bullet "no model IDs found in source"
provider_env=$(grep -rEoh "${SRC_INC[@]}" "${EXCL[@]}" \
  '\b(OPENAI|ANTHROPIC|GEMINI|GOOGLE_API|GOOGLE_GENAI|XAI|MISTRAL|GROQ|DEEPSEEK|FAL|REPLICATE|RUNWAY|HF|HUGGINGFACE|PINECONE|QDRANT|COHERE|ELEVENLABS|OPENROUTER|TOGETHER|AZURE_OPENAI)_[A-Z_]*KEY\b' . 2>/dev/null | sort -u | tr '\n' ' ')
[ -n "$provider_env" ] && bullet "provider key names referenced: $provider_env"
mapfile -t PROMPTS < <(ff 6 -iname '*prompt*' | grep -Ev '\.(png|jpg|jpeg|webp|svg|lock)$' | head -12)
[ ${#PROMPTS[@]} -gt 0 ] && [ -n "${PROMPTS[0]}" ] && bullet "prompt-related files: ${PROMPTS[*]}"

section "Agent & contributor docs"
for f in CLAUDE.md AGENTS.md .cursorrules CONTRIBUTING.md README.md docs/ARCHITECTURE.md ARCHITECTURE.md; do
  [ -f "$f" ] && bullet "$f"
done
[ -d .cursor/rules ] && bullet ".cursor/rules/"
[ -d .claude ] && bullet ".claude/ (project Claude config)"

section "Git"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  bullet "branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
  dirty=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
  [ "$dirty" = "0" ] && bullet "working tree: clean" || bullet "working tree: DIRTY ($dirty changed/untracked paths)"
  bullet "last commit: $(git log -1 --format='%h %s (%cr)' 2>/dev/null)"
else
  bullet "not a git repository"
fi
